server:
  port: 8081
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web
    username: root
    password: 212109
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  mail:
    host: smtp.yandex.ru
    username: FastEmaaiil@yandex.ru
    password: EmaaiilFast
    port: 465
    protocol: smtps
    debug: true

amazon:
  bucket: test-backet-ilya
  awsId: YCAJEC2QrKhEprDoVeRIF2WB0
  awsKey: YCNE-vwuDtHSwRIr6FwQtd47UQKVzm_8sIqCu5aR
  serviceEndPoint: storage.yandexcloud.net
  signingRegion: ru-central1
