server:
  port:
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web
    username:
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      host:
      port:
      database: test
mail:
  host:
  username:
  password:
  port:
  protocol: smtps
  debug: true
amazon:
  bucket:
  awsId:
  awsKey:
  serviceEndPoint:
  signingRegion:
jwt:
  secretKey:
front:
  url: