server:
  port: 8081
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: 212109
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: create
    show-sql: true
amazon:
  bucket: test-backet-ilya
  awsId: YCAJEC2QrKhEprDoVeRIF2WB0
  awsKey: YCNE-vwuDtHSwRIr6FwQtd47UQKVzm_8sIqCu5aR