
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  mail:
    host: smtp.yandex.ru
    username: uw@dru.su
    password: 12345678
    port: 465
    protocol: smtps
mail:
  debug: true

amazon:
  bucket: test-backet-ilya
  awsId: YCAJEC2QrKhEprDoVeRIF2WB0
  awsKey: YCNE-vwuDtHSwRIr6FwQtd47UQKVzm_8sIqCu5aR
