server:
  port: 8081
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: 212109
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: validate
    show-sql: true

