server:
  port: 8081
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/marketplace
    username: root
    password: 212109
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
amazon:
  bucket: test-backet-ilya
  awsId: YCAJEC2QrKhEprDoVeRIF2WB0
  awsKey: YCNE-vwuDtHSwRIr6FwQtd47UQKVzm_8sIqCu5aR