server:
  port: 8081
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/marketplace
    username: root
    password: 212109
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true