version: '3'

services:
  app:
    build: .
    container_name: 'java-app'
    ports:
      - 8081:8081
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/marketplace'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=212109'
    depends_on:
      - postgres
    restart: always
  postgres:
    image: 'postgres:10'
    container_name: 'java_postgres'
    environment:
      - 'POSTGRES_PASSWORD=212109'
      - 'POSTGRES_DB=marketplace'
    restart: always