version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java_postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=212109'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=marketplace'
  app:
    build: .
    container_name: 'java-app'
    depends_on:
      - db
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres'
      - 'SPRING_DATASOURCE_USERNAME=jdbc:postgresql://db:5432/postgres'
      - 'SPRING_DATASOURCE_PASSWORD=jdbc:postgresql://db:5432/212109'
      - 'SPRING_JPA_HIBERNATE_DLL_AUTO=update'
